
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ck_project
{

using System;
    using System.Collections.Generic;
    
public partial class lead_source_report
{

    public string source_name { get; set; }

    public int Huntington { get; set; }

    public int Charleston { get; set; }

    public int Lewisburg { get; set; }

    public Nullable<int> total { get; set; }

}

}
