//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck_project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tax()
        {
            this.taxes_leads = new HashSet<taxes_leads>();
        }

        public int? tax_number { get; set; }
        public string tax_anme { get; set; }

        public double tax_value { get; set; }
        public string city { get; set; }

        [Required(ErrorMessage = "please Enter State")]
        public string state { get; set; }
        public string county { get; set; }
        public string zipcode { get; set; }

        [Required(ErrorMessage = "please Select Valid Date")]
        public Nullable<System.DateTime> start_date { get; set; }
        [Required(ErrorMessage = "please Select Valid Date")]
        public Nullable<System.DateTime> end_date { get; set; }
        public bool deleted { get; set; }
        public bool in_city { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taxes_leads> taxes_leads { get; set; }
    }
}
